In [5]:
%matplotlib inline
import os
import datetime
import pytz
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import mglearn
from IPython import display

data = pd.read_csv(
    os.path.join(mglearn.datasets.DATA_PATH, "adult.data"),
    header=None, index_col = False,
    names=['age', 'workclass', 'fnlwgt', 'education', 'education-num',
           'marital-status', 'occupation', 'relationship', 'race', 'gender',
           'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']
)

data = data[['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income']]
display.display(data)

age          workclass    education   gender  hours-per-week  \
0       39          State-gov    Bachelors     Male              40   
1       50   Self-emp-not-inc    Bachelors     Male              13   
2       38            Private      HS-grad     Male              40   
3       53            Private         11th     Male              40   
4       28            Private    Bachelors   Female              40   
...    ...                ...          ...      ...             ...   
32556   27            Private   Assoc-acdm   Female              38   
32557   40            Private      HS-grad     Male              40   
32558   58            Private      HS-grad   Female              40   
32559   22            Private      HS-grad     Male              20   
32560   52       Self-emp-inc      HS-grad   Female              40   

               occupation  income  
0            Adm-clerical   <=50K  
1         Exec-managerial   <=50K  
2       Handlers-cleaners   <=50K  
3       Handlers-cleaners   <=50K  
4          Prof-specialty   <=50K  
...                   ...     ...  
32556        Tech-support   <=50K  
32557   Machine-op-inspct    >50K  
32558        Adm-clerical   <=50K  
32559        Adm-clerical   <=50K  
32560     Exec-managerial    >50K  

[32561 rows x 7 columns]

In [6]:
data.gender.value_counts()

 Male      21790
 Female    10771
Name: gender, dtype: int64

In [7]:
print("original columns:\n", list(data.columns))
data_dummy = pd.get_dummies(data)
print("dummy data columns:\n", list(data_dummy))

original columns:
 ['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income']
dummy data columns:
 ['age', 'hours-per-week', 'workclass_ ?', 'workclass_ Federal-gov', 'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private', 'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc', 'workclass_ State-gov', 'workclass_ Without-pay', 'education_ 10th', 'education_ 11th', 'education_ 12th', 'education_ 1st-4th', 'education_ 5th-6th', 'education_ 7th-8th', 'education_ 9th', 'education_ Assoc-acdm', 'education_ Assoc-voc', 'education_ Bachelors', 'education_ Doctorate', 'education_ HS-grad', 'education_ Masters', 'education_ Preschool', 'education_ Prof-school', 'education_ Some-college', 'gender_ Female', 'gender_ Male', 'occupation_ ?', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'oc

In [9]:
display.display(data_dummy.head())

age  hours-per-week  workclass_ ?  workclass_ Federal-gov  \
0   39              40             0                       0   
1   50              13             0                       0   
2   38              40             0                       0   
3   53              40             0                       0   
4   28              40             0                       0   

   workclass_ Local-gov  workclass_ Never-worked  workclass_ Private  \
0                     0                        0                   0   
1                     0                        0                   0   
2                     0                        0                   1   
3                     0                        0                   1   
4                     0                        0                   1   

   workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  workclass_ State-gov  \
0                        0                            0                     1   
1                        0                            1                     0   
2                        0                            0                     0   
3                        0                            0                     0   
4                        0                            0                     0   

   ...  occupation_ Machine-op-inspct  occupation_ Other-service  \
0  ...                              0                          0   
1  ...                              0                          0   
2  ...                              0                          0   
3  ...                              0                          0   
4  ...                              0                          0   

   occupation_ Priv-house-serv  occupation_ Prof-specialty  \
0                            0                           0   
1                            0                           0   
2                            0                           0   
3                            0                           0   
4                            0                           1   

   occupation_ Protective-serv  occupation_ Sales  occupation_ Tech-support  \
0                            0                  0                         0   
1                            0                  0                         0   
2                            0                  0                         0   
3                            0                  0                         0   
4                            0                  0                         0   

   occupation_ Transport-moving  income_ <=50K  income_ >50K  
0                             0              1             0  
1                             0              1             0  
2                             0              1             0  
3                             0              1             0  
4                             0              1             0  

[5 rows x 46 columns]

In [14]:
features = data_dummy.loc[:, 'age':'occupation_ Transport-moving']

X = features.values
y = data_dummy['income_ >50K'].values

In [16]:
print("X shape: {} y shape: {}".format(X.shape, y.shape))

X shape: (32561, 44) y shape: (32561,)


In [17]:
from sklearn.preprocessing import OneHotEncoder

demo_df = pd.DataFrame({'숫자 특성':[0, 1, 2, 1], '범주형 특성':['양말', '여우', '양말', '상자']})

ohe = OneHotEncoder(sparse=False)
print(ohe.fit_transform(demo_df))

[[1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]]


In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

ct = ColumnTransformer([
    ('scaling', StandardScaler(), ['age', 'hours-per-week']),
    ('onehot', OneHotEncoder(sparse=False), ['workclass', 'education', 'gender', 'occupation'])
])

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

data_features = data.drop('income', axis=1)
X_train, X_test, y_train, y_test = train_test_split(
    data_features, data.income, random_state=0
)

ct.fit(X_train)
X_train_trans = ct.transform(X_train)

print(X_train_trans.shape)

(24420, 44)


In [21]:
rnd = np.random.RandomState(0)
X_org = rnd.normal(size=(1000,3))
w = rnd.normal(size=3)

X = rnd.poisson(10 * np.exp(X_org))
y = np.dot(X_org, w)

print(X[:10, 0])

[ 56  81  25  20  27  18  12  21 109   7]
